export const categories = [
  {
    _id: "cat-cotton",
    slug: "cotton",
    name: "Cotton",
    description: "Poplin, canvas, twill and voile in combed and organic grades.",
    icon: "Sprout",
  },
  {
    _id: "cat-silk",
    slug: "silk",
    name: "Silk",
    description: "Charmeuse, chiffon, dupioni and mulberry silk for premium lines.",
    icon: "Sparkles",
  },
  {
    _id: "cat-linen",
    slug: "linen",
    name: "Linen",
    description: "European flax linen in garment and home-weight constructions.",
    icon: "Wind",
  },
  {
    _id: "cat-denim",
    slug: "denim",
    name: "Denim",
    description: "Rigid and stretch denim from 8oz chambray to 14oz raw selvedge.",
    icon: "Layers",
  },
  {
    _id: "cat-wool",
    slug: "wool",
    name: "Wool & Cashmere",
    description: "Merino, flannel and cashmere blends for outerwear and tailoring.",
    icon: "CloudSnow",
  },
  {
    _id: "cat-synthetic",
    slug: "synthetic",
    name: "Synthetic & Technical",
    description: "Performance polyester, nylon ripstop and recycled technical wovens.",
    icon: "Zap",
  },
  {
    _id: "cat-knits",
    slug: "knits",
    name: "Knits & Jersey",
    description: "Single jersey, interlock and ribbing for activewear and basics.",
    icon: "CircleDot",
  },
  {
    _id: "cat-sustainable",
    slug: "sustainable",
    name: "Sustainable & Organic",
    description: "GOTS-certified and recycled fibers with full traceability.",
    icon: "Leaf",
  },
]

export const suppliers = [
  {
    key: "sup-01",
    name: "Anantara Textile Mills",
    email: "contact@anantaratextiles.example",
    description:
      "Vertically integrated cotton mill supplying combed, organic and recycled cotton fabrics to apparel brands worldwide.",
    phone: "+91 422 555 0142",
    addressLine1: "14 Mill Road, SIDCO Industrial Estate",
    city: "Coimbatore",
    state: "Tamil Nadu",
    postalCode: "641021",
    country: "India",
    operatingHours: "Mon–Sat, 9:00–18:00 IST",
    categories: ["cat-cotton", "cat-sustainable"],
    defaultMoq: 200,
    verified: true,
    rating: 4.8,
    yearsInBusiness: 22,
    responseTime: "Usually responds within 2 hours",
    certifications: ["GOTS", "OEKO-TEX Standard 100"],
  },
  {
    key: "sup-02",
    name: "Hangzhou Silk Union",
    email: "contact@hangzhousilk.example",
    description:
      "Heritage silk weaving house producing charmeuse, chiffon and dupioni for eveningwear and premium linings.",
    phone: "+86 571 5550 1873",
    addressLine1: "88 Wensan Road",
    city: "Hangzhou",
    state: "Zhejiang",
    postalCode: "310012",
    country: "China",
    operatingHours: "Mon–Fri, 8:30–17:30 CST",
    categories: ["cat-silk"],
    defaultMoq: 100,
    verified: true,
    rating: 4.6,
    yearsInBusiness: 18,
    responseTime: "Usually responds within 4 hours",
    certifications: ["ISO 9001"],
  },
  {
    key: "sup-03",
    name: "Filati di Como",
    email: "contact@filatidicomo.example",
    description:
      "Fourth-generation Italian mill specializing in fine wool, cashmere blends and suiting fabrics.",
    phone: "+39 031 555 0198",
    addressLine1: "Via Torno 12",
    city: "Como",
    state: "Lombardy",
    postalCode: "22100",
    country: "Italy",
    operatingHours: "Mon–Fri, 8:00–17:00 CET",
    categories: ["cat-wool"],
    defaultMoq: 80,
    verified: true,
    rating: 4.9,
    yearsInBusiness: 41,
    responseTime: "Usually responds within a day",
    certifications: ["OEKO-TEX Standard 100", "GRS"],
  },
  {
    key: "sup-04",
    name: "Ege Denim Co.",
    email: "contact@egedenim.example",
    description:
      "Shuttle-loom and modern denim production from 8oz chambray to 14oz raw selvedge, serving premium denim brands.",
    phone: "+90 232 555 0176",
    addressLine1: "Atatürk Organize Sanayi Bölgesi, 4. Cadde No: 22",
    city: "Izmir",
    state: "Izmir",
    postalCode: "35620",
    country: "Turkey",
    operatingHours: "Mon–Fri, 8:00–17:00 TRT",
    categories: ["cat-denim"],
    defaultMoq: 150,
    verified: true,
    rating: 4.7,
    yearsInBusiness: 15,
    responseTime: "Usually responds within 3 hours",
    certifications: ["ISO 9001", "BCI"],
  },
  {
    key: "sup-05",
    name: "Porto Linen Works",
    email: "contact@portolinen.example",
    description:
      "Family-run linen weaver working exclusively with certified European flax for garment and home-weight fabrics.",
    phone: "+351 22 555 0164",
    addressLine1: "Rua de Santos Pousada 210",
    city: "Porto",
    postalCode: "4000-478",
    country: "Portugal",
    operatingHours: "Mon–Fri, 9:00–18:00 WET",
    categories: ["cat-linen"],
    defaultMoq: 100,
    verified: false,
    rating: 4.4,
    yearsInBusiness: 9,
    responseTime: "Usually responds within a day",
    certifications: ["European Flax"],
  },
  {
    key: "sup-06",
    name: "Carolina Performance Fabrics",
    email: "contact@carolinaperformance.example",
    description:
      "Technical textile manufacturer producing recycled and performance synthetics for outerwear and activewear.",
    phone: "+1 336 555 0129",
    addressLine1: "1400 Textile Drive",
    city: "Greensboro",
    state: "NC",
    postalCode: "27405",
    country: "United States",
    operatingHours: "Mon–Fri, 8:00–17:00 EST",
    categories: ["cat-synthetic"],
    defaultMoq: 200,
    verified: true,
    rating: 4.5,
    yearsInBusiness: 12,
    responseTime: "Usually responds within 6 hours",
    certifications: ["bluesign", "Repreve Certified"],
  },
  {
    key: "sup-07",
    name: "Dhaka Knit Collective",
    email: "contact@dhakaknit.example",
    description:
      "Large-scale knit fabric producer supplying jersey, interlock and rib knits for basics and activewear programs.",
    phone: "+880 2 555 0187",
    addressLine1: "Plot 45, Export Processing Zone",
    city: "Dhaka",
    postalCode: "1230",
    country: "Bangladesh",
    operatingHours: "Sat–Thu, 8:00–17:00 BST",
    categories: ["cat-knits"],
    defaultMoq: 200,
    verified: true,
    rating: 4.3,
    yearsInBusiness: 11,
    responseTime: "Usually responds within 5 hours",
    certifications: ["GOTS", "WRAP"],
  },
  {
    key: "sup-08",
    name: "Saigon Knit Mills",
    email: "contact@saigonknit.example",
    description:
      "A rapidly scaling knitwear and garment-fabric manufacturer supplying jersey, terry and poly-cotton blends to global apparel brands.",
    phone: "+84 28 555 0143",
    addressLine1: "56 Tan Thuan Dong Street, Tan Thuan Export Processing Zone",
    city: "Ho Chi Minh City",
    postalCode: "700000",
    country: "Vietnam",
    operatingHours: "Mon–Sat, 8:00–17:00 ICT",
    categories: ["cat-knits", "cat-synthetic"],
    defaultMoq: 250,
    verified: true,
    rating: 4.5,
    yearsInBusiness: 8,
    responseTime: "Usually responds within 5 hours",
    certifications: ["WRAP", "ISO 9001"],
  },
]

export const products = [
  {
    slug: "combed-cotton-poplin-ivory",
    name: "Combed Cotton Poplin",
    categoryKey: "cat-cotton",
    fabricType: "Poplin",
    color: "Ivory White",
    colorHex: "#F5F1E8",
    composition: "100% Combed Cotton",
    weightGsm: 120,
    widthCm: 150,
    pricePerUnit: 4.2,
    currency: "USD",
    unit: "meter",
    moq: 300,
    availability: "in-stock",
    leadTimeDays: 7,
    supplierKey: "sup-01",
    rating: 4.7,
    reviewCount: 128,
    description:
      "A fine-count combed cotton poplin with a crisp hand and subtle sheen, milled for shirting and lightweight dresses. Pre-shrunk and mercerized for a smooth, consistent surface.",
    tags: ["shirting", "lightweight", "mercerized"],
    featured: true,
    createdAt: "2026-05-02",
  },
  {
    slug: "organic-cotton-canvas-charcoal",
    name: "Organic Cotton Canvas",
    categoryKey: "cat-cotton",
    fabricType: "Canvas",
    color: "Charcoal Black",
    colorHex: "#1C1C1E",
    composition: "100% Organic Cotton",
    weightGsm: 310,
    widthCm: 152,
    pricePerUnit: 6.8,
    currency: "USD",
    unit: "meter",
    moq: 200,
    availability: "in-stock",
    leadTimeDays: 10,
    supplierKey: "sup-01",
    rating: 4.8,
    reviewCount: 96,
    description:
      "Heavyweight GOTS-certified organic canvas built for structured bags, workwear and outerwear. Tight plain weave resists abrasion while staying breathable.",
    tags: ["heavyweight", "organic", "workwear"],
    featured: false,
    createdAt: "2026-04-18",
  },
  {
    slug: "cotton-twill-camel",
    name: "Brushed Cotton Twill",
    categoryKey: "cat-cotton",
    fabricType: "Twill",
    color: "Camel Tan",
    colorHex: "#C19A6B",
    composition: "98% Cotton, 2% Elastane",
    weightGsm: 260,
    widthCm: 148,
    pricePerUnit: 5.5,
    currency: "USD",
    unit: "meter",
    moq: 250,
    availability: "limited",
    leadTimeDays: 14,
    supplierKey: "sup-01",
    rating: 4.5,
    reviewCount: 61,
    description:
      "A soft-brushed stretch twill with a fine diagonal rib, ideal for tailored trousers and structured jackets that need a touch of give.",
    tags: ["stretch", "twill", "tailoring"],
    featured: false,
    createdAt: "2026-03-30",
  },
  {
    slug: "cotton-voile-blush",
    name: "Featherweight Cotton Voile",
    categoryKey: "cat-cotton",
    fabricType: "Voile",
    color: "Blush Pink",
    colorHex: "#E3B8B0",
    composition: "100% Cotton",
    weightGsm: 70,
    widthCm: 140,
    pricePerUnit: 3.6,
    currency: "USD",
    unit: "meter",
    moq: 400,
    availability: "in-stock",
    leadTimeDays: 6,
    supplierKey: "sup-01",
    rating: 4.4,
    reviewCount: 44,
    description:
      "Sheer, airy voile with a soft drape, perfect for summer blouses, linings and layered silhouettes.",
    tags: ["sheer", "summer", "lightweight"],
    featured: false,
    createdAt: "2026-02-14",
  },
  {
    slug: "mulberry-silk-charmeuse-navy",
    name: "Mulberry Silk Charmeuse",
    categoryKey: "cat-silk",
    fabricType: "Charmeuse",
    color: "Deep Navy",
    colorHex: "#1B2A4A",
    composition: "100% Mulberry Silk",
    weightGsm: 19,
    widthCm: 114,
    pricePerUnit: 18.5,
    currency: "USD",
    unit: "meter",
    moq: 100,
    availability: "in-stock",
    leadTimeDays: 12,
    supplierKey: "sup-02",
    rating: 4.9,
    reviewCount: 87,
    description:
      "Grade 6A mulberry silk with a liquid drape and lustrous face, milled for eveningwear, lingerie and premium linings.",
    tags: ["luxury", "drape", "eveningwear"],
    featured: true,
    createdAt: "2026-05-10",
  },
  {
    slug: "silk-chiffon-ivory",
    name: "Pure Silk Chiffon",
    categoryKey: "cat-silk",
    fabricType: "Chiffon",
    color: "Ivory White",
    colorHex: "#F5F1E8",
    composition: "100% Silk",
    weightGsm: 15,
    widthCm: 112,
    pricePerUnit: 15.2,
    currency: "USD",
    unit: "meter",
    moq: 150,
    availability: "made-to-order",
    leadTimeDays: 21,
    supplierKey: "sup-02",
    rating: 4.6,
    reviewCount: 39,
    description:
      "Translucent, softly textured chiffon that floats beautifully in gathers and layers, a staple for bridal and eveningwear.",
    tags: ["sheer", "bridal", "luxury"],
    featured: false,
    createdAt: "2026-01-22",
  },
  {
    slug: "silk-dupioni-rust",
    name: "Slubbed Silk Dupioni",
    categoryKey: "cat-silk",
    fabricType: "Dupioni",
    color: "Rust Orange",
    colorHex: "#B5502D",
    composition: "100% Silk",
    weightGsm: 90,
    widthCm: 112,
    pricePerUnit: 12.8,
    currency: "USD",
    unit: "meter",
    moq: 120,
    availability: "in-stock",
    leadTimeDays: 10,
    supplierKey: "sup-02",
    rating: 4.5,
    reviewCount: 52,
    description:
      "Crisp dupioni with natural slubs and a subtle sheen, holding structured shapes well for occasionwear and accents.",
    tags: ["textured", "structured", "occasionwear"],
    featured: false,
    createdAt: "2026-04-02",
  },
  {
    slug: "european-flax-linen-natural",
    name: "European Flax Linen",
    categoryKey: "cat-linen",
    fabricType: "Plain Weave",
    color: "Natural Beige",
    colorHex: "#D8C9B0",
    composition: "100% Linen",
    weightGsm: 175,
    widthCm: 140,
    pricePerUnit: 9.4,
    currency: "USD",
    unit: "meter",
    moq: 200,
    availability: "in-stock",
    leadTimeDays: 9,
    supplierKey: "sup-05",
    rating: 4.7,
    reviewCount: 73,
    description:
      "Certified European Flax linen with a soft, stonewashed hand that stays breathable and durable for garments and home textiles alike.",
    tags: ["breathable", "certified", "stonewashed"],
    featured: true,
    createdAt: "2026-03-11",
  },
  {
    slug: "linen-blend-sage",
    name: "Cotton-Linen Blend",
    categoryKey: "cat-linen",
    fabricType: "Blend Weave",
    color: "Sage Green",
    colorHex: "#8A9A7B",
    composition: "55% Linen, 45% Cotton",
    weightGsm: 155,
    widthCm: 145,
    pricePerUnit: 6.9,
    currency: "USD",
    unit: "meter",
    moq: 250,
    availability: "in-stock",
    leadTimeDays: 8,
    supplierKey: "sup-05",
    rating: 4.3,
    reviewCount: 28,
    description:
      "A softer, more affordable alternative to pure linen with reduced creasing and a gentle drape for everyday garments.",
    tags: ["blend", "everyday", "low-crease"],
    featured: false,
    createdAt: "2026-02-27",
  },
  {
    slug: "heavy-linen-canvas-charcoal",
    name: "Heavyweight Linen Canvas",
    categoryKey: "cat-linen",
    fabricType: "Canvas",
    color: "Charcoal Black",
    colorHex: "#1C1C1E",
    composition: "100% Linen",
    weightGsm: 320,
    widthCm: 140,
    pricePerUnit: 13.6,
    currency: "USD",
    unit: "meter",
    moq: 100,
    availability: "limited",
    leadTimeDays: 15,
    supplierKey: "sup-05",
    rating: 4.6,
    reviewCount: 19,
    description:
      "Dense, structured linen canvas for upholstery-weight garments, bags and outerwear that need real body.",
    tags: ["heavyweight", "structured", "outerwear"],
    featured: false,
    createdAt: "2026-01-08",
  },
  {
    slug: "raw-selvedge-denim-indigo",
    name: "14oz Raw Selvedge Denim",
    categoryKey: "cat-denim",
    fabricType: "Selvedge Denim",
    color: "Indigo Blue",
    colorHex: "#2A3B5C",
    composition: "100% Cotton",
    weightGsm: 470,
    widthCm: 82,
    pricePerUnit: 11.2,
    currency: "USD",
    unit: "meter",
    moq: 150,
    availability: "in-stock",
    leadTimeDays: 18,
    supplierKey: "sup-04",
    rating: 4.9,
    reviewCount: 104,
    description:
      "Shuttle-loomed raw selvedge denim with deep rope-dyed indigo, prized for its fade characteristics and rigid, break-in hand.",
    tags: ["selvedge", "rigid", "premium"],
    featured: true,
    createdAt: "2026-05-20",
  },
  {
    slug: "stretch-denim-indigo-light",
    name: "9oz Comfort Stretch Denim",
    categoryKey: "cat-denim",
    fabricType: "Stretch Denim",
    color: "Indigo Blue",
    colorHex: "#3D5170",
    composition: "98% Cotton, 2% Elastane",
    weightGsm: 305,
    widthCm: 145,
    pricePerUnit: 7.4,
    currency: "USD",
    unit: "meter",
    moq: 300,
    availability: "in-stock",
    leadTimeDays: 12,
    supplierKey: "sup-04",
    rating: 4.4,
    reviewCount: 67,
    description:
      "Mid-weight stretch denim engineered for four-way recovery, well suited to fitted silhouettes and everyday denim lines.",
    tags: ["stretch", "everyday", "four-way"],
    featured: false,
    createdAt: "2026-04-09",
  },
  {
    slug: "chambray-denim-slate",
    name: "Lightweight Chambray",
    categoryKey: "cat-denim",
    fabricType: "Chambray",
    color: "Slate Grey",
    colorHex: "#6E7681",
    composition: "100% Cotton",
    weightGsm: 135,
    widthCm: 150,
    pricePerUnit: 5.1,
    currency: "USD",
    unit: "meter",
    moq: 250,
    availability: "in-stock",
    leadTimeDays: 8,
    supplierKey: "sup-04",
    rating: 4.2,
    reviewCount: 33,
    description:
      "A softly textured plain-weave chambray with denim character at a fraction of the weight, suited to shirting and dresses.",
    tags: ["lightweight", "shirting", "versatile"],
    featured: false,
    createdAt: "2026-03-05",
  },
  {
    slug: "merino-wool-flannel-navy",
    name: "Merino Wool Flannel",
    categoryKey: "cat-wool",
    fabricType: "Flannel",
    color: "Deep Navy",
    colorHex: "#1B2A4A",
    composition: "100% Merino Wool",
    weightGsm: 280,
    widthCm: 150,
    pricePerUnit: 16.4,
    currency: "USD",
    unit: "meter",
    moq: 120,
    availability: "in-stock",
    leadTimeDays: 16,
    supplierKey: "sup-03",
    rating: 4.8,
    reviewCount: 58,
    description:
      "Brushed merino flannel with a soft nap and warm hand, milled in Italy for tailored jackets and outerwear.",
    tags: ["warm", "tailoring", "italian-milled"],
    featured: true,
    createdAt: "2026-04-27",
  },
  {
    slug: "cashmere-wool-blend-burgundy",
    name: "Cashmere-Wool Blend Coating",
    categoryKey: "cat-wool",
    fabricType: "Coating",
    color: "Burgundy",
    colorHex: "#6E2C3A",
    composition: "30% Cashmere, 70% Wool",
    weightGsm: 420,
    widthCm: 150,
    pricePerUnit: 34.0,
    currency: "USD",
    unit: "meter",
    moq: 80,
    availability: "limited",
    leadTimeDays: 20,
    supplierKey: "sup-03",
    rating: 4.9,
    reviewCount: 41,
    description:
      "A dense, luxurious coating fabric with real cashmere softness against a durable wool base, built for outerwear that lasts.",
    tags: ["luxury", "outerwear", "coating"],
    featured: true,
    createdAt: "2026-05-15",
  },
  {
    slug: "worsted-wool-suiting-charcoal",
    name: "Worsted Wool Suiting",
    categoryKey: "cat-wool",
    fabricType: "Suiting",
    color: "Charcoal Black",
    colorHex: "#232326",
    composition: "100% Wool",
    weightGsm: 240,
    widthCm: 150,
    pricePerUnit: 21.5,
    currency: "USD",
    unit: "meter",
    moq: 100,
    availability: "made-to-order",
    leadTimeDays: 25,
    supplierKey: "sup-03",
    rating: 4.7,
    reviewCount: 22,
    description:
      "Fine worsted wool with a smooth, refined surface, the standard choice for tailored suiting and structured blazers.",
    tags: ["suiting", "refined", "tailoring"],
    featured: false,
    createdAt: "2026-02-19",
  },
  {
    slug: "recycled-ripstop-nylon-black",
    name: "Recycled Ripstop Nylon",
    categoryKey: "cat-synthetic",
    fabricType: "Ripstop",
    color: "Charcoal Black",
    colorHex: "#1C1C1E",
    composition: "100% Recycled Nylon",
    weightGsm: 70,
    widthCm: 150,
    pricePerUnit: 8.2,
    currency: "USD",
    unit: "meter",
    moq: 200,
    availability: "in-stock",
    leadTimeDays: 11,
    supplierKey: "sup-06",
    rating: 4.5,
    reviewCount: 47,
    description:
      "Tear-resistant ripstop woven from recycled nylon yarns with a DWR finish, built for technical outerwear and packs.",
    tags: ["technical", "recycled", "water-resistant"],
    featured: false,
    createdAt: "2026-03-22",
  },
  {
    slug: "performance-polyester-slate",
    name: "4-Way Stretch Performance Polyester",
    categoryKey: "cat-synthetic",
    fabricType: "Performance Weave",
    color: "Slate Grey",
    colorHex: "#6E7681",
    composition: "88% Polyester, 12% Elastane",
    weightGsm: 210,
    widthCm: 152,
    pricePerUnit: 7.9,
    currency: "USD",
    unit: "meter",
    moq: 300,
    availability: "in-stock",
    leadTimeDays: 10,
    supplierKey: "sup-06",
    rating: 4.4,
    reviewCount: 65,
    description:
      "Moisture-wicking performance fabric with strong four-way recovery, developed for activewear and technical apparel.",
    tags: ["activewear", "moisture-wicking", "stretch"],
    featured: false,
    createdAt: "2026-04-14",
  },
  {
    slug: "recycled-polyester-taffeta-navy",
    name: "Recycled Polyester Taffeta",
    categoryKey: "cat-synthetic",
    fabricType: "Taffeta",
    color: "Deep Navy",
    colorHex: "#1B2A4A",
    composition: "100% Recycled Polyester",
    weightGsm: 60,
    widthCm: 150,
    pricePerUnit: 4.8,
    currency: "USD",
    unit: "meter",
    moq: 350,
    availability: "in-stock",
    leadTimeDays: 9,
    supplierKey: "sup-06",
    rating: 4.1,
    reviewCount: 24,
    description:
      "A crisp, lightweight taffeta with a subtle sheen, suited to linings and structured outerwear shells.",
    tags: ["linings", "lightweight", "recycled"],
    featured: false,
    createdAt: "2026-01-30",
  },
  {
    slug: "cotton-jersey-off-white",
    name: "Combed Cotton Single Jersey",
    categoryKey: "cat-knits",
    fabricType: "Single Jersey",
    color: "Off White",
    colorHex: "#EDE8DE",
    composition: "95% Cotton, 5% Elastane",
    weightGsm: 180,
    widthCm: 165,
    pricePerUnit: 5.6,
    currency: "USD",
    unit: "meter",
    moq: 300,
    availability: "in-stock",
    leadTimeDays: 8,
    supplierKey: "sup-07",
    rating: 4.6,
    reviewCount: 91,
    description:
      "A staple single jersey with a soft, even face and reliable stretch recovery, the backbone of any basics program.",
    tags: ["basics", "t-shirt", "stretch"],
    featured: true,
    createdAt: "2026-05-06",
  },
  {
    slug: "interlock-knit-blush",
    name: "Cotton-Modal Interlock",
    categoryKey: "cat-knits",
    fabricType: "Interlock",
    color: "Blush Pink",
    colorHex: "#E3B8B0",
    composition: "60% Cotton, 35% Modal, 5% Elastane",
    weightGsm: 220,
    widthCm: 160,
    pricePerUnit: 6.7,
    currency: "USD",
    unit: "meter",
    moq: 250,
    availability: "in-stock",
    leadTimeDays: 9,
    supplierKey: "sup-07",
    rating: 4.5,
    reviewCount: 38,
    description:
      "A smooth, drapey interlock with a modal-boosted softness, ideal for loungewear and elevated essentials.",
    tags: ["loungewear", "soft-hand", "drape"],
    featured: false,
    createdAt: "2026-02-11",
  },
  {
    slug: "rib-knit-charcoal",
    name: "2x2 Cotton Rib Knit",
    categoryKey: "cat-knits",
    fabricType: "Rib Knit",
    color: "Charcoal Black",
    colorHex: "#1C1C1E",
    composition: "94% Cotton, 6% Elastane",
    weightGsm: 260,
    widthCm: 90,
    pricePerUnit: 6.1,
    currency: "USD",
    unit: "meter",
    moq: 200,
    availability: "limited",
    leadTimeDays: 10,
    supplierKey: "sup-07",
    rating: 4.3,
    reviewCount: 29,
    description:
      "A dense 2x2 rib with strong recovery, milled narrow for cuffs, collars and fitted knitwear trims.",
    tags: ["trims", "ribbing", "fitted"],
    featured: false,
    createdAt: "2026-03-17",
  },
  {
    slug: "gots-organic-cotton-jersey-sage",
    name: "GOTS Organic Cotton Jersey",
    categoryKey: "cat-sustainable",
    fabricType: "Single Jersey",
    color: "Sage Green",
    colorHex: "#8A9A7B",
    composition: "100% Organic Cotton",
    weightGsm: 165,
    widthCm: 160,
    pricePerUnit: 6.3,
    currency: "USD",
    unit: "meter",
    moq: 200,
    availability: "in-stock",
    leadTimeDays: 10,
    supplierKey: "sup-01",
    rating: 4.8,
    reviewCount: 54,
    description:
      "Fully traceable GOTS-certified organic jersey with a soft, natural hand, a clean option for conscious basics lines.",
    tags: ["organic", "certified", "traceable"],
    featured: true,
    createdAt: "2026-04-23",
  },
  {
    slug: "recycled-cotton-canvas-natural",
    name: "Recycled Cotton Canvas",
    categoryKey: "cat-sustainable",
    fabricType: "Canvas",
    color: "Natural Beige",
    colorHex: "#D8C9B0",
    composition: "80% Recycled Cotton, 20% Recycled Polyester",
    weightGsm: 340,
    widthCm: 150,
    pricePerUnit: 8.9,
    currency: "USD",
    unit: "meter",
    moq: 150,
    availability: "in-stock",
    leadTimeDays: 14,
    supplierKey: "sup-01",
    rating: 4.4,
    reviewCount: 17,
    description:
      "A GRS-certified canvas blended from post-industrial cotton waste, holding up to heavyweight bag and workwear use.",
    tags: ["recycled", "grs-certified", "heavyweight"],
    featured: false,
    createdAt: "2026-01-15",
  },
  {
    slug: "tencel-lyocell-twill-camel",
    name: "TENCEL Lyocell Twill",
    categoryKey: "cat-sustainable",
    fabricType: "Twill",
    color: "Camel Tan",
    colorHex: "#C19A6B",
    composition: "100% TENCEL Lyocell",
    weightGsm: 190,
    widthCm: 145,
    pricePerUnit: 9.8,
    currency: "USD",
    unit: "meter",
    moq: 180,
    availability: "made-to-order",
    leadTimeDays: 22,
    supplierKey: "sup-01",
    rating: 4.7,
    reviewCount: 21,
    description:
      "A closed-loop lyocell twill with a silky drape and natural sheen, biodegradable at end of life.",
    tags: ["biodegradable", "closed-loop", "silky"],
    featured: false,
    createdAt: "2026-05-01",
  },
  {
    slug: "hemp-cotton-blend-slate",
    name: "Hemp-Cotton Blend Canvas",
    categoryKey: "cat-sustainable",
    fabricType: "Canvas",
    color: "Slate Grey",
    colorHex: "#6E7681",
    composition: "55% Hemp, 45% Cotton",
    weightGsm: 290,
    widthCm: 148,
    pricePerUnit: 10.4,
    currency: "USD",
    unit: "meter",
    moq: 150,
    availability: "in-stock",
    leadTimeDays: 13,
    supplierKey: "sup-01",
    rating: 4.6,
    reviewCount: 26,
    description:
      "A low-input hemp blend with excellent durability and a naturally textured surface that softens with wash.",
    tags: ["low-impact", "durable", "textured"],
    featured: false,
    createdAt: "2026-02-08",
  },
  {
    slug: "silk-wool-blend-burgundy",
    name: "Silk-Wool Suiting Blend",
    categoryKey: "cat-wool",
    fabricType: "Suiting",
    color: "Burgundy",
    colorHex: "#6E2C3A",
    composition: "40% Silk, 60% Wool",
    weightGsm: 230,
    widthCm: 150,
    pricePerUnit: 26.0,
    currency: "USD",
    unit: "meter",
    moq: 90,
    availability: "limited",
    leadTimeDays: 19,
    supplierKey: "sup-03",
    rating: 4.8,
    reviewCount: 15,
    description:
      "A refined blend combining silk's subtle luster with wool's structure, built for premium tailoring lines.",
    tags: ["luxury", "suiting", "lustrous"],
    featured: false,
    createdAt: "2026-03-27",
  },
  {
    slug: "technical-softshell-charcoal",
    name: "Bonded Technical Softshell",
    categoryKey: "cat-synthetic",
    fabricType: "Softshell",
    color: "Charcoal Black",
    colorHex: "#1C1C1E",
    composition: "92% Polyester, 8% Elastane, Fleece Bonded",
    weightGsm: 340,
    widthCm: 150,
    pricePerUnit: 13.2,
    currency: "USD",
    unit: "meter",
    moq: 200,
    availability: "in-stock",
    leadTimeDays: 15,
    supplierKey: "sup-06",
    rating: 4.6,
    reviewCount: 33,
    description:
      "A three-layer bonded softshell with a brushed fleece backing, windproof membrane and mechanical stretch for outerwear.",
    tags: ["outerwear", "windproof", "bonded"],
    featured: true,
    createdAt: "2026-04-30",
  },
  {
    slug: "cotton-corduroy-olive",
    name: "8-Wale Cotton Corduroy",
    categoryKey: "cat-cotton",
    fabricType: "Corduroy",
    color: "Olive Green",
    colorHex: "#6B7A4F",
    composition: "100% Cotton",
    weightGsm: 320,
    widthCm: 140,
    pricePerUnit: 7.6,
    currency: "USD",
    unit: "meter",
    moq: 200,
    availability: "in-stock",
    leadTimeDays: 12,
    supplierKey: "sup-01",
    rating: 4.6,
    reviewCount: 34,
    description:
      "A classic 8-wale corduroy with a deep, even pile and soft brushed back, built for outerwear, trousers and accessories that need texture.",
    tags: ["textured", "wale", "outerwear"],
    featured: false,
    createdAt: "2026-05-24",
  },
  {
    slug: "cotton-oxford-sky-blue",
    name: "Classic Cotton Oxford",
    categoryKey: "cat-cotton",
    fabricType: "Oxford",
    color: "Sky Blue",
    colorHex: "#A9C6E8",
    composition: "100% Cotton",
    weightGsm: 145,
    widthCm: 150,
    pricePerUnit: 4.9,
    currency: "USD",
    unit: "meter",
    moq: 300,
    availability: "in-stock",
    leadTimeDays: 8,
    supplierKey: "sup-01",
    rating: 4.5,
    reviewCount: 47,
    description:
      "A basketweave cotton Oxford with a substantial, breathable hand, the standard for button-down shirting.",
    tags: ["shirting", "basketweave", "breathable"],
    featured: false,
    createdAt: "2026-06-02",
  },
  {
    slug: "cotton-seersucker-blue-stripe",
    name: "Puckered Cotton Seersucker",
    categoryKey: "cat-cotton",
    fabricType: "Seersucker",
    color: "Blue Stripe",
    colorHex: "#4F7CAC",
    composition: "100% Cotton",
    weightGsm: 125,
    widthCm: 145,
    pricePerUnit: 5.3,
    currency: "USD",
    unit: "meter",
    moq: 250,
    availability: "in-stock",
    leadTimeDays: 9,
    supplierKey: "sup-01",
    rating: 4.4,
    reviewCount: 21,
    description:
      "A crinkled, self-striped seersucker that sits away from the skin for warm-weather shirting and summer suiting.",
    tags: ["summer", "puckered", "warm-weather"],
    featured: false,
    createdAt: "2026-06-10",
  },
  {
    slug: "cotton-jacquard-gold",
    name: "Damask Cotton Jacquard",
    categoryKey: "cat-cotton",
    fabricType: "Jacquard",
    color: "Antique Gold",
    colorHex: "#B8973E",
    composition: "100% Cotton",
    weightGsm: 210,
    widthCm: 148,
    pricePerUnit: 8.4,
    currency: "USD",
    unit: "meter",
    moq: 150,
    availability: "in-stock",
    leadTimeDays: 15,
    supplierKey: "sup-01",
    rating: 4.7,
    reviewCount: 18,
    description:
      "A woven-in damask pattern with a subtle tonal sheen, adding structure and pattern without a single print.",
    tags: ["patterned", "structured", "woven-design"],
    featured: false,
    createdAt: "2026-05-29",
  },
  {
    slug: "silk-rayon-velvet-emerald",
    name: "Silk-Rayon Devoré Velvet",
    categoryKey: "cat-silk",
    fabricType: "Velvet",
    color: "Emerald Green",
    colorHex: "#1F5D4D",
    composition: "70% Rayon, 30% Silk",
    weightGsm: 280,
    widthCm: 112,
    pricePerUnit: 22.5,
    currency: "USD",
    unit: "meter",
    moq: 80,
    availability: "limited",
    leadTimeDays: 18,
    supplierKey: "sup-02",
    rating: 4.8,
    reviewCount: 12,
    description:
      "A deep-pile silk-rayon velvet with a plush hand and rich color depth, milled for eveningwear and statement pieces.",
    tags: ["luxury", "plush", "eveningwear"],
    featured: true,
    createdAt: "2026-06-14",
  },
  {
    slug: "silk-georgette-dusty-rose",
    name: "Crinkled Silk Georgette",
    categoryKey: "cat-silk",
    fabricType: "Georgette",
    color: "Dusty Rose",
    colorHex: "#C98C8C",
    composition: "100% Silk",
    weightGsm: 60,
    widthCm: 114,
    pricePerUnit: 14.6,
    currency: "USD",
    unit: "meter",
    moq: 120,
    availability: "made-to-order",
    leadTimeDays: 14,
    supplierKey: "sup-02",
    rating: 4.6,
    reviewCount: 16,
    description:
      "A matte, slightly crinkled georgette with airy movement, a step sheerer and drapier than chiffon for flowing silhouettes.",
    tags: ["sheer", "matte", "drape"],
    featured: false,
    createdAt: "2026-05-18",
  },
  {
    slug: "wool-tweed-heather-grey",
    name: "Donegal Wool Tweed",
    categoryKey: "cat-wool",
    fabricType: "Tweed",
    color: "Heather Grey",
    colorHex: "#8B8D92",
    composition: "95% Wool, 5% Nylon",
    weightGsm: 380,
    widthCm: 150,
    pricePerUnit: 19.8,
    currency: "USD",
    unit: "meter",
    moq: 100,
    availability: "limited",
    leadTimeDays: 20,
    supplierKey: "sup-03",
    rating: 4.8,
    reviewCount: 20,
    description:
      "A flecked Donegal-style tweed with a rustic, nubby texture, a heritage choice for outerwear and structured tailoring.",
    tags: ["heritage", "flecked", "outerwear"],
    featured: false,
    createdAt: "2026-04-05",
  },
  {
    slug: "recycled-wool-flannel-heather",
    name: "Recycled Wool Flannel",
    categoryKey: "cat-sustainable",
    fabricType: "Flannel",
    color: "Heather Grey",
    colorHex: "#8B8D92",
    composition: "70% Recycled Wool, 30% Recycled Polyester",
    weightGsm: 300,
    widthCm: 150,
    pricePerUnit: 17.5,
    currency: "USD",
    unit: "meter",
    moq: 100,
    availability: "limited",
    leadTimeDays: 18,
    supplierKey: "sup-03",
    rating: 4.5,
    reviewCount: 13,
    description:
      "A GRS-certified flannel rebuilt from post-consumer wool and recycled polyester, keeping the warmth without virgin fiber.",
    tags: ["recycled", "grs-certified", "warm"],
    featured: false,
    createdAt: "2026-06-06",
  },
  {
    slug: "polyester-crepe-black",
    name: "Matte Polyester Crepe",
    categoryKey: "cat-synthetic",
    fabricType: "Crepe",
    color: "Jet Black",
    colorHex: "#101012",
    composition: "100% Polyester",
    weightGsm: 110,
    widthCm: 150,
    pricePerUnit: 5.4,
    currency: "USD",
    unit: "meter",
    moq: 300,
    availability: "in-stock",
    leadTimeDays: 9,
    supplierKey: "sup-06",
    rating: 4.3,
    reviewCount: 29,
    description:
      "A pebbled, matte-finish crepe with excellent drape and zero shine, a dependable base for tops, dresses and linings.",
    tags: ["matte", "drape", "affordable"],
    featured: false,
    createdAt: "2026-05-12",
  },
  {
    slug: "polar-fleece-charcoal-melange",
    name: "Anti-Pill Polar Fleece",
    categoryKey: "cat-synthetic",
    fabricType: "Fleece",
    color: "Charcoal Melange",
    colorHex: "#4A4A4E",
    composition: "100% Polyester",
    weightGsm: 260,
    widthCm: 150,
    pricePerUnit: 6.9,
    currency: "USD",
    unit: "meter",
    moq: 250,
    availability: "in-stock",
    leadTimeDays: 8,
    supplierKey: "sup-06",
    rating: 4.4,
    reviewCount: 41,
    description:
      "A brushed, anti-pill polar fleece with dense loft and warmth-to-weight, a staple for midlayers and loungewear.",
    tags: ["midlayer", "warm", "anti-pill"],
    featured: false,
    createdAt: "2026-03-19",
  },
  {
    slug: "duchess-satin-champagne",
    name: "Polyester Duchess Satin",
    categoryKey: "cat-synthetic",
    fabricType: "Satin",
    color: "Champagne",
    colorHex: "#E9D9B7",
    composition: "100% Polyester",
    weightGsm: 130,
    widthCm: 150,
    pricePerUnit: 6.2,
    currency: "USD",
    unit: "meter",
    moq: 250,
    availability: "in-stock",
    leadTimeDays: 10,
    supplierKey: "sup-06",
    rating: 4.2,
    reviewCount: 25,
    description:
      "A structured duchess satin with a high-luster face, holding sculptural shapes for eveningwear at a fraction of silk's cost.",
    tags: ["lustrous", "structured", "budget-friendly"],
    featured: false,
    createdAt: "2026-02-23",
  },
  {
    slug: "french-terry-off-white",
    name: "Brushed-Back French Terry",
    categoryKey: "cat-knits",
    fabricType: "French Terry",
    color: "Off White",
    colorHex: "#EDE8DE",
    composition: "80% Cotton, 20% Polyester",
    weightGsm: 240,
    widthCm: 165,
    pricePerUnit: 6.5,
    currency: "USD",
    unit: "meter",
    moq: 300,
    availability: "in-stock",
    leadTimeDays: 11,
    supplierKey: "sup-08",
    rating: 4.5,
    reviewCount: 22,
    description:
      "A looped-face, brushed-back French terry with a soft interior, the go-to knit for sweatshirts and joggers.",
    tags: ["sweatshirt", "brushed", "loungewear"],
    featured: true,
    createdAt: "2026-06-18",
  },
  {
    slug: "cotton-waffle-knit-natural",
    name: "Cotton Waffle Knit",
    categoryKey: "cat-knits",
    fabricType: "Waffle Knit",
    color: "Natural Beige",
    colorHex: "#D8C9B0",
    composition: "100% Cotton",
    weightGsm: 200,
    widthCm: 160,
    pricePerUnit: 6.8,
    currency: "USD",
    unit: "meter",
    moq: 250,
    availability: "in-stock",
    leadTimeDays: 10,
    supplierKey: "sup-08",
    rating: 4.4,
    reviewCount: 14,
    description:
      "A textured honeycomb waffle knit with natural thermal pockets, suited to base layers and textured essentials.",
    tags: ["textured", "thermal", "essentials"],
    featured: false,
    createdAt: "2026-06-22",
  },
  {
    slug: "poly-cotton-jersey-heather-grey",
    name: "Poly-Cotton Blend Jersey",
    categoryKey: "cat-knits",
    fabricType: "Single Jersey",
    color: "Heather Grey",
    colorHex: "#8B8D92",
    composition: "65% Polyester, 35% Cotton",
    weightGsm: 175,
    widthCm: 165,
    pricePerUnit: 4.7,
    currency: "USD",
    unit: "meter",
    moq: 350,
    availability: "in-stock",
    leadTimeDays: 9,
    supplierKey: "sup-08",
    rating: 4.2,
    reviewCount: 31,
    description:
      "An affordable poly-cotton jersey with a heathered face and good shape retention, a workhorse for high-volume basics.",
    tags: ["basics", "high-volume", "affordable"],
    featured: false,
    createdAt: "2026-05-08",
  },
  {
    slug: "bamboo-modal-jersey-sage",
    name: "Bamboo-Modal Jersey",
    categoryKey: "cat-sustainable",
    fabricType: "Single Jersey",
    color: "Sage Green",
    colorHex: "#8A9A7B",
    composition: "95% Bamboo Viscose, 5% Elastane",
    weightGsm: 190,
    widthCm: 160,
    pricePerUnit: 7.5,
    currency: "USD",
    unit: "meter",
    moq: 200,
    availability: "in-stock",
    leadTimeDays: 12,
    supplierKey: "sup-01",
    rating: 4.7,
    reviewCount: 19,
    description:
      "A silky-soft bamboo-viscose jersey with natural moisture-wicking and a cooling hand, a plant-based alternative to modal alone.",
    tags: ["bamboo", "moisture-wicking", "soft-hand"],
    featured: false,
    createdAt: "2026-06-28",
  },
]
